CREATE TABLE AID(
COLLEGE_ID VARCHAR2(10) CONSTRAINT FK_AID REFERENCES COLLEGE ON DELETE CASCADE,
ORGANIZATION VARCHAR2(20), SCHOLARSHIP_NAME VARCHAR2(30), 
COUNTRY VARCHAR2(10) NOT NULL,
CONSTRAINT PK_AID PRIMARY KEY(COLLEGE_ID, SCHOLARSHIP_NAME));
