CREATE TABLE COLLEGE(
COLLEGE_ID VARCHAR2(10) CONSTRAINT PK_COLLEGE CHECK(COLLEGE_ID LIKE 'C%') PRIMARY KEY,
PASSWORD VARCHAR2(20), 
COLLEGE_NAME VARCHAR2(30),
EMAIL VARCHAR2(30) CONSTRAINT VALID_EMAIL_COLLEGE CHECK(EMAIL LIKE '%@%.%') UNIQUE NOT NULL,
STREET VARCHAR2(20), CITY VARCHAR2(20), STATE VARCHAR2(20),
COUNTRY VARCHAR2(20) CONSTRAINT VALID_COLLEGE_COUNTRY NOT NULL,
ZIP_CODE NUMBER(6));
