CREATE TABLE DEGREE(
DEGREE_ID VARCHAR2(10) CONSTRAINT PK_DEGREE CHECK(DEGREE_ID LIKE 'D%') PRIMARY KEY,
COLLEGE_ID VARCHAR2(10) CONSTRAINT FK_COLLEGE_OFFERS REFERENCES COLLEGE ON DELETE CASCADE,
STREAM_ID VARCHAR2(10) CONSTRAINT FK_STREAM_OFFERS REFERENCES STREAM ON DELETE CASCADE,
DEGREE_TYPE VARCHAR2(10), 
DEGREE_NAME VARCHAR2(10),
SEATS NUMBER(4) CONSTRAINT VALID_SEATS CHECK(SEATS>0), FEE NUMBER(6,2) CONSTRAINT VALID_FEE CHECK(FEE>0) );
