CREATE TABLE REQUIREMENTS(
COLLEGE_ID VARCHAR2(10) CONSTRAINT FK_COLLEGE_REQ REFERENCES COLLEGE ON DELETE CASCADE,
STREAM_ID VARCHAR2(10) CONSTRAINT FK_STREAM_REQ REFERENCES STREAM ON DELETE CASCADE,
DEGREE_ID VARCHAR2(10) CONSTRAINT FK_DEGREE_REQ REFERENCES DEGREE ON DELETE CASCADE,
YEARS NUMBER(4) CONSTRAINT VALID_YEARS_REQ CHECK(YEARS>0), 
CGPA NUMBER(3,2) CONSTRAINT VALID_CGPA_REQ CHECK(CGPA>0) NOT NULL,
IELTS NUMBER(2,1) CONSTRAINT VALID_IELTS_REQ CHECK(IELTS BETWEEN 0 AND 9),
TOEFL NUMBER(3) CONSTRAINT VALID_TOEFL_REQ CHECK(TOEFL BETWEEN 0 AND 120),
GRE NUMBER(3) CONSTRAINT VALID_GRE_REQ CHECK(GRE BETWEEN 0 AND 340),
GATE NUMBER(4) CONSTRAINT VALID_GATE_REQ CHECK(GATE BETWEEN 0 AND 1000),
GMAT NUMBER(3) CONSTRAINT VALID_GMAT_REQ CHECK(GMAT BETWEEN 0 AND 800),
CAT NUMBER(3) CONSTRAINT VALID_CAT_REQ CHECK(CAT BETWEEN 0 AND 300),
CONSTRAINT PK_REQ PRIMARY KEY(COLLEGE_ID, STREAM_ID, DEGREE_ID));
