CREATE TABLE SCORES(
STUDENT_ID VARCHAR2(10) CONSTRAINT FK_SCORES REFERENCES STUDENT ON DELETE CASCADE,
YEARS NUMBER(4) CONSTRAINT VALID_YEARS_SCORE CHECK(YEARS>0), 
CGPA NUMBER(3,2) CONSTRAINT VALID_CGPA_SCORE CHECK(CGPA>0) NOT NULL,
IELTS NUMBER(2,1) CONSTRAINT VALID_IELTS_SCORE CHECK(IELTS BETWEEN 0 AND 9),
TOEFL NUMBER(3) CONSTRAINT VALID_TOEFL_SCORE CHECK(TOEFL BETWEEN 0 AND 120),
GRE NUMBER(3) CONSTRAINT VALID_GRE_SCORE CHECK(GRE BETWEEN 0 AND 340),
GATE NUMBER(4) CONSTRAINT VALID_GATE_SCORE CHECK(GATE BETWEEN 0 AND 1000),
GMAT NUMBER(3) CONSTRAINT VALID_GMAT_SCORE CHECK(GMAT BETWEEN 0 AND 800),
CAT NUMBER(3) CONSTRAINT VALID_CAT_SCORE CHECK(CAT BETWEEN 0 AND 300),
CONSTRAINT PK_SCORE PRIMARY KEY(STUDENT_ID));
