CREATE TABLE STUDENT(
STUDENT_ID VARCHAR2(10) CONSTRAINT PK_STUDENT PRIMARY KEY CHECK(STUDENT_ID LIKE 'S%'),
PASSWORD VARCHAR2(20), 
FIRST_NAME VARCHAR2(20), 
LAST_NAME VARCHAR2(20),
PHONE NUMBER(10) CONSTRAINT UNQ_PHONE_STUDENT UNIQUE NOT NULL, 
EMAIL VARCHAR2(30) CONSTRAINT VALID_EMAIL_STUDENT CHECK(EMAIL LIKE '%@%.%') UNIQUE NOT NULL,
DEGREE_TYPE VARCHAR2(10), 
COLLEGE_NAME VARCHAR2(30),
COLLEGE_ID VARCHAR2(10) CONSTRAINT FK_STUDENT REFERENCES COLLEGE,
ENROLMENT_DATE DATE NOT NULL, 
GRADUATION_DATE DATE NOT NULL,
CREDITS NUMBER(4) CONSTRAINT VALID_CREDITS CHECK(CREDITS>0), 
CONSTRAINT VALID_GRADUATION CHECK(GRADUATION_DATE>ENROLMENT_DATE));
